# Generated by Django 5.1 on 2025-11-19 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atraccion',
            fields=[
                ('id_atr', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(max_length=100)),
                ('altura_min', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cli', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=50)),
                ('fecha_reg', models.DateField(auto_now_add=True)),
                ('id_atr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_parque.atraccion')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_emp', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('puesto', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=15)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_atr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_parque.atraccion')),
            ],
        ),
        migrations.AddField(
            model_name='atraccion',
            name='id_emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_parque.empleado'),
        ),
    ]
