# Generated by Django 5.1 on 2025-11-20 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_parque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id_bol', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_com', models.DateField()),
                ('metodo_pago', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_reg',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id_atr',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='sin_email@parque.com', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_cli',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_bol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_parque.boleto'),
        ),
        migrations.CreateModel(
            name='RestTienda',
            fields=[
                ('id_local', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=30)),
                ('ubicacion', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
                ('id_emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_parque.empleado')),
            ],
        ),
    ]
